name: Lint Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Lint Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # or the version your project requires

    - name: Install Dependencies
      run: npm install

    - name: Run Lint
      run: npm run lint # Replace this with your lint command
